#' gsnImportFGSEA
#'
#' @description Add FGSEA search data to a GSNData object, as generated by the the FGSEA package. The data set can be
#' either in the form of a data.frame or specified as import from a delimited text file. (See Details below)
#'
#' @param object A GSNData object.
#' @param pathways_data An (optional) data.frame containing the results of FGSEA analysis. (Either this or the
#' \code{filename} argument must be set.
#' @param filename An (optional) filename for data sets read from a text file containing FGSEA results. This is ignored
#' if the \code{pathways_data} argument is set.
#' @param id_col (optional) A character vector of length 1 indicating the name of the column used as a key for gene
#' sets or modules. This is normally the \code{pathway} field of FGSEA data, which must be the same as the names of gene
#' sets specified in the tmod object or in the list of gene set vectors specified with the \code{geneSetCollection}
#' argument used when building the gene set network. By default this value is \code{'pathway'}. The IDs must correspond
#' to the names of the gene sets provided, or an error will be thrown. **NOTE:** In the tmod::tmodImportMSigDB function
#' provided by the tmod package, the default ID is an MSigDB accession, but FGSEA data sets do not use this accession.
#' The \code{NAME} column used in FGSEA results set corresponds instead to the \code{STANDARD_NAME} field in the MSigDB
#' XML database file. This \code{STANDARD_NAME} field is not preserved by the standard \code{tmod::tmodImportMSigDB}
#' utility function, but instead reformatted converting underscores to spaces and non-initial letters to lower case.
#' Therefore, when using FGSEA data sets with an MSigDB gene set collection imported using \code{tmod::tmodImportMSigDB}
#' the \code{NAME} fields need to be mapped to the \code{ID} or vice versa.
#' @param stat_col (optional) A character vector of length 1 indicating the name of the column used as a statistic
#' to evaluate the quality of pathways results. The function scans through possible \code{stat_col} values
#' (\code{"pval"}, and \code{"padj"}, and uses the first one it finds.
#' @param sig_order (optional) Either \code{'loToHi'} (default) or \code{'hiToLo'} depending on the statistic used to
#' evaluate pathways results.
#' @param n_col (optional) Specifies the column containing the number of genes in the gene set. Generally, this is the number
#' of genes in the gene set that are attested in an expression data set (Defaults to 'size').
#' @param sep A separator for text file import, defaults to "\\t". Ignored if \code{filename} is not specified.
#'
#' @return This returns a GSNData object containing imported pathways data.
#'
#' @details
#' Note: An error is thrown if all gene set IDs in the genePresenceAbsense are not present in the FGSEA \code{pathway} column.
#' However, if there are gene set IDs present in the pathways data that are absent from the \code{$genePresenceAbsence}
#' matrix, then this method emits a warning. It also checks for the standard FGSEA data set column names, and if some are
#' missing, it will emit a warning.
#'
#' @export
#'
#'
#' @seealso
#'  \code{\link{gsnAddPathwaysData}}
#'  \code{\link{gsnImportCERNO}}
#'  \code{\link{gsnImportGSEA}}
#'  \code{\link{gsnImportGSNORA}}
#'  \code{\link{gsnImportGenericPathways}}
#'
#' @importFrom utils read.table
#'
gsnImportFGSEA <- function (object, pathways_data = NULL, filename = NULL, id_col = NULL,
                            stat_col = NULL, sig_order = NULL, n_col = NULL, sep = "\t")
{
  stopifnot("GSNData" %in% class(object))
  if (is.null(pathways_data) && is.null(filename))
    stop("The 'pathways_data' and 'filename' arguments cannot both be NULL.")
  if (is.null(pathways_data)) {
    pathways_data <- utils::read.table(file = filename, header = TRUE,
                                       sep = sep, stringsAsFactors = FALSE, check.names = FALSE)
  }
  if (!is.null(sig_order) && !sig_order %in% c("loToHi", "hiToLo"))
    stop("Invalid sig_order: ", as.character(sig_order))
  if (!is.null(stat_col) && !stat_col %in% colnames(pathways_data))
    stop("stat_col '", stat_col, "' not found in pathways data.")
  field_names <- colnames(pathways_data)
  gsea_fieldnames <- c("pathway", "pval", "padj", "log2err", "ES", "NES", "size", "leadingEdge")
  if (length(missing_fieldnames <- gsea_fieldnames[!make.names(gsea_fieldnames) %in%
                                                   make.names(field_names)]) > 0) {
    warning("Pathways data are missing the following GSEA fields:",
            paste0(missing_fieldnames, collapse = ", "), "\n")
  }
  pathways <- list(data = pathways_data, type = "fgsea")
  if ("pathway" %in% field_names)
    pathways$id_col <- "pathway"
  stat_cols <- c("padj", "pval")
  if (length(present_stat_cols <- field_names[field_names %in%
                                              stat_cols]) > 0) {
    pathways$stat_col <- present_stat_cols[1]
    pathways$sig_order <- "loToHi"
  }
  n_cols <- c("size")
  if (length(present_n_cols <- field_names[field_names %in%
                                           n_cols]) > 0) {
    pathways$n_col <- present_n_cols[1]
  }
  if ("pathway" %in% field_names && !"Title" %in% field_names)
    pathways$data$Title <- stringr::str_to_title(gsub(pattern = "_",
                                                      replacement = " ", x = pathways$data$pathway))
  if (!is.null(id_col))
    pathways$id_col <- id_col
  if (!is.null(stat_col))
    pathways$stat_col <- stat_col
  if (!is.null(sig_order))
    pathways$sig_order <- sig_order
  if (!is.null(n_col))
    pathways$n_col <- n_col
  if (is.null(pathways$id_col))
    stop("id_col (ID Column specification) required.")
  if (!all(colnames(object$genePresenceAbsence) %in% pathways$data[[pathways$id_col]]))
    stop("Error: Pathways data do not match gene set collection. They are missing gene sets from gene set collection.")
  if (!all(pathways$data[[pathways$id_col]] %in% colnames(object$genePresenceAbsence)))
    warning("Warning: Pathways data do not match gene set collection. They contain gene sets not present in gene set collection.\n")
  object$pathways <- pathways
  object
}


# gsnAddPathwaysData <- function (object, pathways_data, type = NULL, id_col = NULL,
#                                 stat_col = NULL, sig_order = NULL, stat_col_2 = NULL, sig_order_2 = NULL,
#                                 n_col = NULL)
# {
#   stopifnot("GSNData" %in% class(object))
#   field_names <- colnames(pathways_data)
#   if ((!is.null(type) && type == "cerno") | all(c("ID", "cerno",
#                                                   "adj.P.Val") %in% field_names)) {
#     message("Using CERNO import.")
#     object <- gsnImportCERNO(object = object, pathways_data,
#                              id_col = id_col, stat_col = stat_col, sig_order = sig_order,
#                              n_col = n_col)
#   }
#   else if ((!is.null(type) && type == "gsea") || (all(c("NAME",
#                                                         "ES", "NES") %in% field_names) && any(c("FDR q-val",
#                                                                                                 "FDR.q.val") %in% field_names))) {
#     message("Using GSEA import.")
#     object <- gsnImportGSEA(object = object, pathways_data = pathways_data,
#                             id_col = id_col, stat_col = stat_col, sig_order = sig_order,
#                             n_col = n_col)
#   }
#   else if ((!is.null(type) && type == "gsnora") || (all(c("ID",
#                                                           "Title", "Enrichment", "P.1S") %in% field_names))) {
#     message("Using GSN-ORA import.")
#     object <- gsnImportGSNORA(object = object, pathways_data = pathways_data,
#                               id_col = id_col, stat_col = stat_col, sig_order = sig_order,
#                               n_col = n_col)
#   }
#   else if ((!is.null(type) && type == "david") || (all(c("Category",
#                                                          "Term", "Count", "%", "PValue", "Genes", "List Total",
#                                                          "Pop Hits", "Pop Total", "Fold Enrichment", "Bonferroni",
#                                                          "Benjamini", "FDR") %in% field_names))) {
#     message("Using DAVID import.")
#     object <- gsnImportDAVID(object = object, pathways_data = pathways_data,
#                              id_col = id_col, stat_col = stat_col, sig_order = sig_order,
#                              n_col = n_col)
#   }
#   else if ((!is.null(type) && type == "fgsna") || (all(c("pathway", "pval", "padj", "log2err",
#                                                          "ES", "NES", "size", "leadingEdge") %in% field_names))) {
#     message("Using fgsna import.")
#     object <- gsnImportFGSEA(object = object, pathways_data = pathways_data,
#                              id_col = id_col, stat_col = stat_col, sig_order = sig_order,
#                              n_col = n_col)
#   }
#   else {
#     message("Using generic pathways import.")
#     object <- gsnImportGenericPathways(object = object, pathways_data = pathways_data,
#                                        type = type, id_col = id_col, stat_col = stat_col,
#                                        sig_order = sig_order)
#   }
#   if (!is.null(stat_col_2)) {
#     if (!stat_col_2 %in% colnames(object$pathways$data)) {
#       stop("stat_col_2 '", stat_col_2, "' not found in pathways data.")
#     }
#     else {
#       object$pathways$stat_col_2 <- stat_col_2
#     }
#   }
#   if (!is.null(sig_order_2)) {
#     if (!sig_order_2 %in% c("loToHi", "hiToLo")) {
#       stop("Invalid sig_order_2: ", as.character(sig_order_2))
#     }
#     else {
#       object$pathways$sig_order_2 <- sig_order_2
#     }
#   }
#   object
# }
